name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  # Different concurrency groups for PR and push
  # PR: <workflow>-<pr-branch-name>
  # push: <workflow>-main as we want to cancel workflow if another push to main while this runs
  # github.head_ref is only set when the workflow was triggered by a pull_request and it
  # contains the value of the source branch of the PR.
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  AWS_REGION: eu-west-1

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_CI }}
          role-session-name: run-${{ github.run_id }}
      - run: aws sts get-caller-identity
      - name: Get tofu version from .opentofu-version
        run: echo "tofu_version=$(cat .opentofu-version)" >> $GITHUB_OUTPUT
        id: get_tofu_version
        working-directory: tf
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ steps.get_tofu_version.outputs.tofu_version }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - run: npm ci
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "src/"
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-pr-review
          level: warning
      - run: npm run build
      # Testing would be here, but maybe not on PR checks
      # TODO: Run tofu plan here and post to PR
      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: build
          path: dist/
      - run: tofu init && tofu plan -out plan.tfplan
        working-directory: tf
      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'push' }}
        with:
          name: tf
          path: tf/plan.tfplan

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    # only runs when it's a push event (and this workflow only triggers with push to the main branch)
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Get tofu version from .opentofu-version
        run: echo "tofu_version=$(cat .opentofu-version)" >> $GITHUB_STATE
        id: tofu_version
        working-directory: tf
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: steps.tofu_version.outputs.tofu_version
      - uses: actions/download-artifact@v4
        name: "Download build"
        with:
          name: build
          path: dist/

